package com.lavie.randochat.utils

object Constants {
    const val FIREBASE_DB_URL =
        "https://rando-chat-332bd-default-rtdb.asia-southeast1.firebasedatabase.app"
    const val RELOAD_USER_TIMEOUT = 10000L
    const val SAVE_USER_TIMEOUT = 15000L
    const val USERS = "users"
    const val ID = "id"
    const val EMAIL = "email"
    const val NICKNAME = "nickname"
    const val IS_ONLINE = "isOnline"
    const val IS_ACTIVE = "isActive"
    const val PARTICIPANTS_ID = "participantIds"
    const val ACTIVE = "active"
    const val IS_DISABLED = "isDisabled"
    const val LAST_UPDATED = "lastUpdated"
    const val LAST_MESSAGE = "lastMessage"
    const val WAITING_USERS = "waiting_users"
    const val CHAT_ROOMS = "chat_rooms"
    const val MATCH_NOTIFICATIONS = "match_notifications"
    const val MATCH_TIMEOUT = 60000L
    const val LOGIN_SCREEN = "login"
    const val REGISTER_SCREEN = "register"
    const val START_CHAT_SCREEN = "start_chat"
    const val CHAT_SCREEN = "chat"
    const val STATUS = "status"
    const val STATUS_WAITING = "waiting"
    const val STATUS_MATCHED = "matched"
    const val MATCHING = "matching"
    const val TIMESTAMP = "timestamp"
    const val CHAT_TYPE = "chatType"
    const val ROOM_ID = "roomId"
    const val PARTNER_ID = "partnerId"
    const val WELCOME_SCREEN = "welcome"
    const val SETTINGS_SCREEN = "settings"
    const val MESSAGES = "messages"
    const val DD_MM_YYYY_HH_MM = "dd/MM/yyyy HH:mm"
    const val HH_MM = "HH:mm"
    const val DD_MM_HH_MM = "dd/MM HH:mm"
    const val EEEE_HH_MM = "EEEE HH:mm"
    const val VI = "vi"
    const val TIME_GAP_MINUTES = 60
    const val CHECK_USER_TIMEOUT = 1000L
    const val SPLASH_SCREEN = "splash"
    const val SPLASH_SCREEN_LOGIN = "splash_login"
    const val SPLASH_MODE_LOGIN = "splash_login"
    const val SPLASH_MODE_MATCHING = "splash_matching"
    const val MODE = "mode"
    const val MESSAGE_ID = "messageId"
    const val APP_PREFS = "app_prefs"
    const val FCM_TOKENS = "fcm_tokens"
    const val TYPE = "type"
    const val CONTENT = "content"
    const val SINGLE_CLICK_TIMEOUT = 600L
    const val SYSTEM = "system"
    const val PAGE_SIZE_MESSAGES = 50
    const val TYPING = "typing"
    const val CACHED_USER_ID = "cached_user_id"
    const val CACHED_USER_EMAIL = "cached_user_email"
    const val CACHED_USER_NICKNAME = "cached_user_nickname"
    const val CACHED_ROOM_ID = "cached_active_room"
    const val SENDER_ID = "senderId"
    const val CONTENT_RES_ID = "contentResId"
    const val ACTIVE_ROOM_ID = "activeRoomId"
    const val LAST_ROOM_ID = "lastRoomId"
    const val CLOUDINARY_CLOUD_NAME = "durhoy6iq"
    const val CLOUDINARY_IMAGE_UPLOAD_PRESET = "Chat_Rando"
    const val CLOUDINARY_AUDIO_UPLOAD_PRESET = "Chat_Rando_Audio"
    const val CLOUDINARY_IMAGE_UPLOAD_URL = "https://api.cloudinary.com/v1_1/$CLOUDINARY_CLOUD_NAME/image/upload"
    const val CLOUDINARY_AUDIO_UPLOAD_URL = "https://api.cloudinary.com/v1_1/$CLOUDINARY_CLOUD_NAME/video/upload"
    const val IMAGE_COMPRESS_QUALITY = 80
    const val IMAGE_FILE_EXTENSION = ".jpg"
    const val IMAGE_FILE_PREFIX = "compressed_"
    const val TEMP_IMAGE_FILE_PREFIX = "upload"
    const val IMAGE_MIME_TYPE = "image/jpeg"
    const val IMAGE_FOLDER_NAME = "/RandoChat"
    const val CLOUDINARY_FORM_KEY_FILE = "file"
    const val CLOUDINARY_FORM_KEY_UPLOAD_PRESET = "upload_preset"
    const val CLOUDINARY_FORM_KEY_FOLDER = "folder"
    const val CLOUDINARY_RESPONSE_KEY_SECURE_URL = "secure_url"
    const val CLOUDINARY_ERROR_PREFIX = "Cloudinary upload failed: "
    const val AUDIO_MIME_TYPE = "audio/m4a"
    const val CLOUDINARY_AUDIO_FOLDER = "chat_audios"
    const val AUDIO_FILE_PREFIX = "voice_"
    const val AUDIO_FILE_EXTENSION = ".m4a"
    const val TEMP_AUDIO_FILE_PREFIX = "temp_audio"
    const val HTTP_PREFIX = "http"
    const val TIME_FORMAT = "%d:%02d"
    const val MILLISECONDS_PER_SECOND = 1000L
    const val SECONDS_PER_MINUTE = 60
    const val VOICE_RECORD_DELAY = 1000L
    const val VOICE_RECORD_DELAY_MAX_SECOND = 180
    const val ZERO_LONG = 0L
    const val DEFAULT_PLAYBACK_POSITION = 0
    const val DEFAULT_TIME_DISPLAY = "0:00"
    const val VOICE_RECORD_MIN_DURATION_TO_SEND = 2L
    const val ERROR_CANNOT_OPEN_INPUT_STREAM = "Không thể mở inputStream từ uri %s (có thể đã mất quyền truy cập hoặc file không còn tồn tại)"
    const val ROUTE_IMAGE_PREVIEW = "imagePreview"
    const val ARG_IMAGE_URL = "imageUrl"
    const val DEFAULT_DURATION_MS = 0L
    const val ROUTE_PASSWORD_CHANGED = "password_changed"
    const val MIME_TYPE_IMAGE = "image/*"
    const val CHAT_DB = "chat-db"
}