name: Auto Review PR with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get PR diff
        id: diff
        run: |
          git fetch origin ${GITHUB_BASE_REF}:${GITHUB_BASE_REF}
          MERGE_BASE=$(git merge-base origin/${{ github.base_ref }} HEAD || echo "")
          if [ -z "$MERGE_BASE" ]; then
            echo "No merge base found. Ensure the base branch and the PR branch have common commits."
            exit 1
          fi
          git diff origin/${{ github.base_ref }} HEAD > diff.txt

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Call ChatGPT API
        id: chatgpt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo -e "Please review the following code diff and provide constructive feedback:\n\n$(cat diff.txt)" > prompt.txt
          ESCAPED_PROMPT=$(cat prompt.txt | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "{\"model\": \"gpt-4o\", \"messages\": [{\"role\": \"user\", \"content\": \"$ESCAPED_PROMPT\"}]}" \
            | jq -r '.choices[0].message.content')
          echo "$RESPONSE" > review.txt

      - name: Post review to PR
        uses: mshick/add-pr-comment@v2
        with:
          message-path: review.txt
